name: Generate Lightroom Translations

on:
  workflow_dispatch:
    inputs:
      languages:
        description: "List of target languages (space-separated, e.g., 'fr de it es'). Leave empty to generate English only."
        required: false
        default: ""

jobs:
  generate-translations:
    runs-on: ubuntu-latest
    name: Extract and update Lightroom translations

    permissions:
      contents: write  # Required to push changes to the repository

    steps:
      # Step 1: Checkout only the main branch (without full history)
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          sparse-checkout: |
            iNaturalist_Identifier.lrplugin/TranslatedStrings_*.txt
            translation.py
            requirements.txt
        # Explanation: Checks out only the necessary files from main (translation files, script, and requirements).

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run translation extraction script
      - name: Run translation extraction script
        run: |
          echo "Running translation.py with languages: '${{ inputs.languages }}'"
          if [ -z "${{ inputs.languages }}" ]; then
            echo "No languages specified — generating English only."
            python3 translation.py
          else
            python3 translation.py ${{ inputs.languages }}
          fi

      # Step 5: Create or switch to the 'translations' branch (orphan)
      - name: Create or switch to 'translations' branch
        run: |
          # Check if the 'translations' branch already exists
          if git ls-remote --exit-code --heads origin translations; then
            git fetch origin translations:translations
            git checkout translations
            # Keep only translation files (remove others)
            git rm -r --ignore-unmatch . || true
            git clean -fd
          else
            # Create a new orphan branch (no history)
            git checkout --orphan translations
            git rm -rf . || true
          fi
        # Explanation: Creates an orphan 'translations' branch (no history) or checks it out if it exists, then clears all files.

      # Step 6: Copy only translation files to the 'translations' branch
      - name: Copy translation files
        run: |
          # Copy the generated translation files from main
          git checkout main -- iNaturalist_Identifier.lrplugin/TranslatedStrings_*.txt
          # Add and commit only the translation files
          git add iNaturalist_Identifier.lrplugin/TranslatedStrings_*.txt
          git commit -m "Update translation files"
          git push origin translations --force
        # Explanation: Copies only the translation files from main to the 'translations' branch and forces push.

      # Step 7: Notify success
      - name: Success notification
        run: echo "✅ Translation files updated in 'translations' branch."
