name: Generate Lightroom Translations

on:
  # Manual trigger only, with optional language input
  workflow_dispatch:
    inputs:
      languages:
        description: "List of target languages (space-separated, e.g. 'fr de it es')"
        required: false
        default: ""

jobs:
  generate-translations:
    runs-on: ubuntu-latest
    name: Extract Lightroom translations

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Step 3: Diagnostic – list all Lua files in the plugin directory
      - name: List Lua files before running script
        run: |
          echo "Listing all Lua files in iNaturalist_Identifier.lrplugin:"
          find iNaturalist_Identifier.lrplugin -type f -name "*.lua" -print

      # Step 4: Run translation extraction script with dynamic language input
      - name: Run translation extraction script
        run: |
          echo "Running translation.py with languages: '${{ inputs.languages }}'"
          python3 translation.py ${{ inputs.languages }}

      # (Optional) Step 5: Display generated English file in logs for verification
      # - name: Display generated English file
      #   run: |
      #     echo "Generated TranslatedStrings_en.txt:"
      #     cat iNaturalist_Identifier.lrplugin/TranslatedStrings_en.txt || echo "No file found."
