name: Generate Lightroom Translations

on:
  workflow_dispatch:
    inputs:
      languages:
        description: "List of target languages (space-separated, e.g., 'fr de it es'). Leave empty to generate English only."
        required: false
        default: ""

jobs:
  generate-translations:
    runs-on: ubuntu-latest
    name: Extract and update Lightroom translations

    permissions:
      contents: write  # Required to push changes to the repository

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        # Explanation: Checks out the repository with write permissions.

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        # Explanation: Configures Python 3.11 for the workflow.

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        # Explanation: Installs all dependencies listed in requirements.txt.

      # Step 4: Run translation extraction script
      - name: Run translation extraction script
        run: |
          echo "Running translation.py with languages: '${{ inputs.languages }}'"
          if [ -z "${{ inputs.languages }}" ]; then
            echo "No languages specified — generating English only."
            python3 translation.py
          else
            python3 translation.py ${{ inputs.languages }}
          fi
        # Explanation: Runs the translation script with the specified languages.

      # Step 5: Create or switch to the 'translations' branch
      - name: Create or switch to 'translations' branch
        run: |
          if git show-ref --quiet refs/heads/translations; then
            git checkout translations
            git pull origin translations
          else
            git checkout -b translations
          fi
        # Explanation: Checks if the 'translations' branch exists. If it does, it checks it out and pulls the latest changes. If not, it creates the branch.

      # Step 6: Commit and push translation updates to 'translations' branch
      - name: Commit and push translation updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Add only translation files
          git add iNaturalist_Identifier.lrplugin/TranslatedStrings_*.txt 2>/dev/null || true

          # Check if there are changes to commit
          if git diff --cached --quiet; then
            echo "No changes detected — skipping commit."
          else
            git commit -m "Update Lightroom translations"
            git push origin translations
            echo "✅ Translation updates pushed to 'translations' branch."
          fi
        # Explanation: Commits and pushes translation updates to the 'translations' branch.
