name: Generate Lightroom Translations

on:
  # Run manually only
  workflow_dispatch:

jobs:
  generate-translations:
    runs-on: ubuntu-latest
    name: Extract Lightroom translations

    steps:
      # Step 1: Check out repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Step 3: List all Lua files in the plugin directory (diagnostic)
      - name: List Lua files before running script
        run: |
          echo "Listing all Lua files in iNaturalist_Identifier.lrplugin:"
          find iNaturalist_Identifier.lrplugin -type f -name "*.lua" -print

      # Step 4: Run translation extraction script
      # The working directory is set so that translation.py scans this folder
      - name: Run translation extraction script
        run: |
          python3 translation.py
        working-directory: ./iNaturalist_Identifier.lrplugin

      # Step 5: Display generated file in the console output
      - name: Display generated file
        run: |
          echo "Generated TranslatedStrings_en.txt:"
          cat iNaturalist_Identifier.lrplugin/TranslatedStrings_en.txt

      # Step 6: Upload result as an artifact (for download from the workflow page)
      - name: Upload generated translation file
        uses: actions/upload-artifact@v4
        with:
          name: TranslatedStrings_en
          path: iNaturalist_Identifier.lrplugin/TranslatedStrings_en.txt
