name: Generate Lightroom Translations

on:
  # Manual trigger from GitHub Actions tab
  workflow_dispatch:
    inputs:
      languages:
        description: "List of target languages (space-separated, e.g. 'fr de it es')"
        required: false
        default: ""

jobs:
  generate-translations:
    runs-on: ubuntu-latest
    name: Extract and update Lightroom translations

    permissions:
      contents: write  # Required to push changes to the repository

    steps:
      # Step 1: Checkout the repository with write access
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Step 3: Diagnostic – list Lua files
      - name: List Lua files
        run: |
          echo "Listing Lua files in iNaturalist_Identifier.lrplugin:"
          find iNaturalist_Identifier.lrplugin -type f -name "*.lua" -print

      # Step 4: Run translation script with language input
      - name: Run translation extraction script
        run: |
          echo "Running translation.py with languages: '${{ inputs.languages }}'"
          python3 translation.py ${{ inputs.languages }}

      # ✅ Step 5: Commit and push directly to main
      - name: Commit and push translation updates
        run: |
          echo "Checking for translation updates..."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Add only translation files
          git add iNaturalist_Identifier.lrplugin/TranslatedStrings_*.txt

          if git diff --cached --quiet; then
            echo "No changes detected — skipping commit."
          else
            git commit -m "translation updates"
            git push origin main
            echo "✅ Pushed translation updates to main branch."
          fi
