name: Generate Lightroom Translations

on:
  workflow_dispatch:
    inputs:
      languages:
        description: "List of target languages (space-separated, e.g., 'fr de it es'). Leave empty to generate English only."
        required: false
        default: ""

jobs:
  generate-translations:
    runs-on: ubuntu-latest
    name: Extract and update Lightroom translations

    permissions:
      contents: write

    steps:
      # Step 1: Checkout the entire repository (lightweight)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1  # Shallow clone to save time

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run translation script
      - name: Run translation script
        run: |
          if [ -z "${{ inputs.languages }}" ]; then
            python3 translation.py
          else
            python3 translation.py ${{ inputs.languages }}
          fi

      # Step 5: Create or reset the 'translations' branch
      - name: Prepare 'translations' branch
        run: |
          # Create a temporary directory for translation files
          mkdir -p temp_translations
          cp -r iNaturalist_Identifier.lrplugin/TranslatedStrings_*.txt temp_translations/

          # Switch to 'translations' branch (orphan if new)
          if git show-ref --quiet refs/heads/translations; then
            git checkout translations
            git rm -r --ignore-unmatch . || true  # Clear existing files
          else
            git checkout --orphan translations
          fi

          # Copy only translation files to the branch
          cp -r temp_translations/* iNaturalist_Identifier.lrplugin/
          rm -rf temp_translations

      # Step 6: Commit and push translation files
      - name: Commit and push translations
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add iNaturalist_Identifier.lrplugin/TranslatedStrings_*.txt
          git commit -m "Update translation files [GitHub Actions]"
          git push origin translations --force
