name: Generate Lightroom Translations

on:
  # Run manually only from the GitHub Actions tab
  workflow_dispatch:

jobs:
  generate-translations:
    runs-on: ubuntu-latest
    name: Extract Lightroom translations

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Step 3: Diagnostic – list all Lua files in the plugin directory
      - name: List Lua files before running script
        run: |
          echo "Listing all Lua files in iNaturalist_Identifier.lrplugin:"
          find iNaturalist_Identifier.lrplugin -type f -name "*.lua" -print

      # Step 4: Run the translation extraction script from the repo root
      # translation.py is located at the repository root
      - name: Run translation extraction script
        run: |
          python3 translation.py

      # Step 5: Display the generated file in workflow logs
      - name: Display generated file
        run: |
          echo "Generated TranslatedStrings_en.txt:"
          cat iNaturalist_Identifier.lrplugin/TranslatedStrings_en.txt

      # Step 6: Upload the generated translation file as a downloadable artifact
      - name: Upload generated translation file
        uses: actions/upload-artifact@v4
        with:
          name: TranslatedStrings_en
          path: iNaturalist_Identifier.lrplugin/TranslatedStrings_en.txt
