name: Generate Lightroom Translations

on:
  workflow_dispatch:
    inputs:
      languages:
        description: "List of target languages (space-separated, e.g., 'fr de it es'). Leave empty to generate English only."
        required: false
        default: ""

jobs:
  generate-translations:
    runs-on: ubuntu-latest
    name: Extract and update Lightroom translations

    permissions:
      contents: write  # Required to push changes to the repository

    steps:
      # Step 1: Checkout the repository with write access
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        # Explanation: Checks out the repository with write permissions to allow pushing changes later.

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        # Explanation: Configures Python 3.11 (stable and recommended version) for the workflow.

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        # Explanation: Upgrades pip and installs all dependencies listed in requirements.txt (e.g., deep-translator).

      # Step 4: Run translation extraction script
      - name: Run translation extraction script
        run: |
          echo "Running translation.py with languages: '${{ inputs.languages }}'"
          if [ -z "${{ inputs.languages }}" ]; then
            echo "No languages specified — generating English only."
            python3 translation.py
          else
            python3 translation.py ${{ inputs.languages }}
          fi
        # Explanation:
        # - Runs the translation.py script.
        # - If no languages are specified, it defaults to generating English only.
        # - If languages are provided (e.g., "fr de"), it generates translations for those languages.

      # Step 5: Commit and push translation updates (if changes exist)
      - name: Commit and push translation updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Add only translation files
          git add iNaturalist_Identifier.lrplugin/TranslatedStrings_*.txt 2>/dev/null || true

          # Check if there are changes to commit
          if git diff --cached --quiet; then
            echo "No changes detected — skipping commit."
          else
            git commit -m "Update Lightroom translations"
            git push origin main
            echo "✅ Translation updates pushed to main branch."
          fi
        # Explanation:
        # - Configures Git to use the GitHub Actions bot for commits.
        # - Adds only the generated translation files (TranslatedStrings_*.txt).
        # - Checks if there are changes before committing.
        # - If changes exist, commits and pushes them to the main branch.
        # - If no changes, skips the commit and logs a message.
