# ============================================================
# Functional Description
# ------------------------------------------------------------
# This GitHub Actions workflow automates the manual release 
# process of the Lightroom plugin `iNaturalist_Identifier.lrplugin`.
#
# New feature:
# - User can choose which branch to release on (`main` or `beta`).
#
# Functional Flow:
# 1. Manual Trigger:
#    - Triggered manually via the `workflow_dispatch` event.
#    - Requires a semantic version number (ex: 1.1.4).
#    - User must select the target branch (`main` or `beta`).
#
# 2. Version Update in Info.lua:
#    - Updates the VERSION block in Info.lua with new version data.
#
# 3. Commit Changes:
#    - Commits Info.lua update to the chosen branch.
#
# 4. Tagging:
#    - Creates and pushes a tag with the version number.
#
# 5. Packaging:
#    - Creates a zip of the plugin directory.
#
# 6. Release Creation:
#    - Publishes a GitHub Release with the zip attached.
# ============================================================

name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number (ex: 1.1.4)"
        required: true
      branch:
        description: "Target branch for release (main or beta)"
        required: true
        default: "main"
        type: choice
        options:
          - main
          - beta

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Update Info.lua
        run: |
          VERSION="${{ github.event.inputs.version }}"
          IFS='.' read -r MAJOR MINOR REVISION <<< "$VERSION"

          awk -v maj=$MAJOR -v min=$MINOR -v rev=$REVISION '
            BEGIN {inblock=0}
            {
              if ($0 ~ /VERSION = {/) {print "    VERSION = {"; inblock=1; next}
              if (inblock && $0 ~ /}/) {
                print "        major = " maj ","
                print "        minor = " min ","
                print "        revision = " rev ","
                print "        build = 0,"
                print "    },"
                inblock=0; next
              }
              if (!inblock) print $0
            }' iNaturalist_Identifier.lrplugin/Info.lua > Info.lua.tmp

          mv Info.lua.tmp iNaturalist_Identifier.lrplugin/Info.lua

      - name: Commit updated Info.lua
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add iNaturalist_Identifier.lrplugin/Info.lua
          git commit -m "Update Info.lua to version ${{ github.event.inputs.version }}"
          git push origin HEAD:${{ github.event.inputs.branch }}

      - name: Create tag
        run: |
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}

      - name: Zip plugin directory
        run: |
          ZIP_NAME="iNaturalist_Identifier.lrplugin-${{ github.event.inputs.version }}.zip"
          zip -r "$ZIP_NAME" iNaturalist_Identifier.lrplugin
          echo "ZIP_FILE=$ZIP_NAME" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          body: "Automated release with Info.lua updated."
          files: ${{ env.ZIP_FILE }}
