name: Prepare release

on:
  push:
    tags:
      - '*.*.*'   # déclenché pour 1.1.4, 2.0.0, etc.

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # commit + release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update Info.lua
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          IFS='.' read -r MAJOR MINOR REVISION <<< "$VERSION"

          awk -v maj=$MAJOR -v min=$MINOR -v rev=$REVISION '
            BEGIN {inblock=0}
            {
              if ($0 ~ /VERSION = {/) {print "    VERSION = {"; inblock=1; next}
              if (inblock && $0 ~ /}/) {
                print "        major = " maj ","
                print "        minor = " min ","
                print "        revision = " rev ","
                print "        build = 0,"
                print "    },"
                inblock=0; next
              }
              if (!inblock) print $0
            }' iNaturalist_Identifier.lrplugin/Info.lua > Info.lua.tmp

          mv Info.lua.tmp iNaturalist_Identifier.lrplugin/Info.lua

      - name: Commit updated Info.lua
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add iNaturalist_Identifier.lrplugin/Info.lua
          git commit -m "Update Info.lua to version ${{ steps.get_version.outputs.version }}"
          git push origin HEAD:main

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Automated release with Info.lua version updated."
